kind: Service
apiVersion: v1
metadata: 
  name: testnewprojectservice
  labels:
    app: testnewprojectservice
spec: 
  ports:    
     - protocol: TCP
       port: 8085
       targetPort: 8080
  selector: 
      app: testnewproject   
  type: NodePort